### ISSUE TITLE
[chore] 프로젝트 세팅

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#1]
# Description ✨
프로젝트 초기 세팅을 진행합니다
main에서 작업 완료 후 브랜치를 분리합니다

# TODO
- [x]  git repo 생성
    - [x]  멤버 추가 (릴리)
- [x]  마크다운 템플릿 생성
- [x]  git rule 규정
    - [x]  최소 리뷰 인원
    - [x]  main, develop은 push 불가
- [x]  프로젝트 생성 (MacOS? iPadOS app)
- [x]  기본 브랜치 지정
- [x]  디스코드 웹훅 연결
- [x]  gitignore 생성 **.xcodeprj 제외**
<img width="2032" alt="스크린샷 2023-09-22 오전 9 51 48" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/c5a13c76-6592-428b-826f-9a940566aeb4">

- [x]  SwiftLint 적용
    **homebrew + swiftlint 각자 설치 필요**
- [x] Firebase 라이브러리 추가
- [x] lint.yml 추가하기

**Comment by dayo2n** [comment]
- [ ] only SwiftUI
- [ ] 서드파티 지양하기
