### ISSUE TITLE
[feat] 애플로그인 구현, CD 구축

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#11]
# Description ✨
애플로그인 기능을 개발할 거예요

# TODO
- [x] User 모델 확인 with @abovocado 
- [x] 애플로그인 구현
- [x] sign up할 때 db setData를 기다리지 않아서 nil exception 발생
- [x] 자동로그인
- [x] 개발자 사이트에 app identifier 등록
- [x] CD 구축 (fastlane)
- [x] ~~#12~~
- @xnoag 
  - [x] hifi 디테일 맞추기 (border clipShape)
  - [x] 창 사이즈 늘어나면 배경이미지도 늘어나게 (이미지 사이즈 자체가 작아서 그런 것 같기도?)
  - [x] Google-Service.plist 새로 바뀜!
  - [x] 팀원들에게 파이어베이스 초대받으라고 공지하기 ~
  - [x] README.md 오타 수정
