### ISSUE TITLE
[feat] time view

### ISSUE THREAD

**Issue by abovocado** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#2]
# Description ✨
[날짜 데이터 받아오고 평일, 휴일, 공휴일 타입을 지정한 구조체]을 개발할 거예요

# TODO
- [x] 날짜 구조체 [요일, 공휴일, 색상]
- [x] 임시 뷰에 타입별로 그려오기
- [ ] 상단에 동적으로 변하는 n월 구현
- [ ] 일요일이면 좌측 보더, 토요일이면 우측 보더
