### ISSUE TITLE
[feat] TimeAxisView

### ISSUE THREAD

**Issue by abovocado** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#24]
# Description ✨
TimeAxisView가 전체 뷰와 함께 작동하도록하는 기능을 구현합니다.

# TODO
- [ ] ScrollPreferenceKey 밖으로 빼기
- [ ] Today선
- [ ] 스크롤 끝날 때마다 새로운 날짜 로드
- [ ] month swipe 애니메이션
- [ ] 많이 보이는 달로 날짜 보정
- [ ] 오늘 날짜 강조
- [ ] 오늘 버튼 누르면 scroll target 이동
