### ISSUE TITLE
[chore] 개발자들을 위한 추가 세팅 

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#3]
# Description ✨
개발자들을 위한 추가 세팅을 진행합니다

# TODO
- [x] gitignore에 GoogleService-Info.plist 추가: 내일 직접 전달
- [x] 이슈, 피알 템플릿에 제목 수정 (대문자를 소문자로)
- [x] 리드미에 코드, 깃 컨벤션 등록
- [x] TCA 라이브러리 추가
- [x] 폴더 구조 생성
- [x] color extension 추가
