### ISSUE TITLE
[feat] plan, planType, Lane에 대한 DB 작업

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#33]
# Description ✨
프로젝트 내에 플랜, 플랜 타입, 레인 단위의 CRUD 기능을 개발할 거예요

# TODO
- [x] navigate to each plan board
- [x] Plan model
- [x] create
- [x] read
  - [ ] plan type 데이터를 전부 읽어오는 것과 키워드로 검색해오는 코드가 한 줄 다른데, 통합할 수 있는 방법 찾기
```
코드
results.filter { $0.title.contains(keyword) }

문제점
전부 읽어오기 위해 keyword를 빈 문자열("")로 전달했는데 전부 false로 인식 
throwing하는 것을 보아하니 코드상의 문제가 있을 것을 염두
```
- [ ] Plan의 description은 언제 어떻게 수정 및 생성되며 보이는지?
- [ ] parentID, childIDs 찾아야함 + **상위 레이어 삭제하면 하위 플랜 아이템들은 다 지워지는 것 맞조 ?**
- [ ] update
- [x] delete - api만 있음

# 2023.10.30. TODO
- [ ] refactor: `laneCollectionPath(projectID).document(laneID).getDocument(as: Lane.self)`: 함수 하나로 줄일 수 있음
- [ ] refactor: emptyOut & delete 함수 하나로 -> delete는 사실 deleteLane에서 구현되어야 함
- [ ] 위 두 개만 마무리하고 이 브랜치받고 update, read는 다른 브랜치, 이슈에서 작업
- [ ] create하면서 생기는 일들 처리하기: onAppear와 store 초기화간의 시간차이

**Comment by dayo2n** [comment]
이 브랜치에서 refactor/54~ 브랜치를 생성해 작업 중이며 추후 54번 브랜치에서 머지될 예정입니다
