### ISSUE TITLE
[feat] ProjectBoardView 삭제/수정/목록

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#36]
# Description ✨
ProjectBoardMainView에서 프로젝트를 삭제하고, 타이틀을 수정할 수 있게 하겠습니다.
ProjectBoardSideView에서 프로젝트의 목록을 구현하겠습니다.

# TODO
- [x] ProjectBoardSideView > Project Item List 구현 -> Foldering / Draggable은 추후에..
- [ ] ProjectBoardMainView > Project Item 삭제
- [ ] ProjectBoardMainView > Poject Title 수정
