### ISSUE TITLE
[feat] LineArea TextField

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#47]
# Description ✨
LineArea에서 그리드를 드래그하고 엔터키를 누르면, **TextField가 플로팅**되는 기능을 구현합니다.

# TODO
- [ ] PlanBar(색칠된 바)가 생성될 때, 왼쪽 상단에 TextField가 열리게 하기
- [ ] TextField가 열리면, 바로 입력할 수 있게 FocusState 적용하기
- [ ] TextField에 Text를 입력하고 엔터키를 누르면, (아직 편집 상태임) ASD 수정할 수 있는 상태되게 하기
- [ ] ESC키를 누르면 편집상태 종료
