### ISSUE TITLE
[feat] TimelineView 보드 구조 레이아웃

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#5]
# Description ✨
TimelineView에서 각 보드의 구조 레이아웃을 제작하겠습니다.

# TODO
- [ ] TabBar 구조 레이아웃
- [ ] Thinking Board 구조 레이아웃
- [ ] ToolBar 구조 레이아웃
- [ ] ScheduleIndex 구조 레이아웃
- [ ] ScheduleGrid 구조 레이아웃
- [ ] TimeIndex  구조 레이아웃
- [ ] PlanRowIndex 구조 레이아웃
- [ ] CategoryGrid 구조 레이아웃
- [ ] PlanGrid 구조 레이아웃
