### ISSUE TITLE
[refactor] 모델 구조에서 Lane을 삭제합니다

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#54]
# Description ✨
모델 Lane이 삭제되었습니다
따라서 Plan이 가지던 laneIDs와 parentLaneID는 삭제되고, childPlanIDs를 이차원 배열로 갖습니다 (사실은 딕셔너리임!)
Lane이 가지던 해당 레인에 대한 최소 최대 일자는 Plan이 갖게되었습니다

# TODO
- [ ] 대 공 사: Lane의 존재를 잊어버리세요~
- [ ] delete()는 절대 안불림 이제
- [ ] 11/3(금) ~ 11/5(일) 릴리와 제나의 태스크
<img width="1266" alt="스크린샷 2023-11-05 오전 6 29 06" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/37587eee-9bb5-48dd-9f2f-76ff9de74800">
