### ISSUE TITLE
[feat] PlanBoard/TimelineLayoutView 코드 작성합니다. 

### ISSUE THREAD

**Issue by OreobrO** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#61]
# Description ✨
현재 변경된 파일구조에 맞춰서 PlanBoard/TimelineLayoutView를 새로이 작성합니다. 

# TODO
- [ ] 기존의 코드 이전하기
- [ ] PlanBoard Color Asset 추가하기
- [ ] Mid-Fi 반영하기
- [ ] LineArea의 PlanItem View 코드 작성하기
- [ ] 트랙패드 스크롤로 index스크롤하는 기능 구현하기
