### ISSUE TITLE
[feat] PlanBoardView를 TCA구조로 온전히 변환하고, 실제 생성되는 Plan과 연동하기 전 관련 UI작업을 진행합니다.

### ISSUE THREAD

**Issue by OreobrO** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#67]
# Description ✨
PlanBoardView를 TCA구조로 온전히 변환하고, 실제 생성되는 Plan과 연동하기 전 관련 UI작업을 진행합니다.

# TODO
- [x] 마우스 드래그로 움직이기 다시 원상복구하기, shift원상복구하기
- [ ] 트랙패드로 드래그 제스쳐 이식하기
- [ ] TimeAxis 주말에 맞춰서 움직이는 영역 구현하기
- [ ] 캘린더 이식하기
- [ ] 샘플 플랜 맵을 활용해서 높이 맞춰진 뷰 만들어내기
- [ ] 단축키 기능들 뷰에서 모두 삭제하고 전역 TCA로 관리하기
