### ISSUE TITLE
[feat] 뷰 구조 TCA 적용

### ISSUE THREAD

**Issue by abovocado** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#69]
# Description ✨
뷰 구조를 TCA로 연결합니다.
Authentication - ProjectBoard - PlanBoard Store간 연결입니다!
(hover, clicke 등 뷰 만지는 것 아님!)

# TODO
- [x] Authentication - projectBoard Navigation삭제
- [x] Authentication - projectBoard store 전달
- [x] Tap해서 화면 갈아끼울 때 id로
- [x] projectBoard ~ projectBoardItem store 전달
- [x] projectBoardItem ~ planBoard store 전달
