### ISSUE TITLE
[feat] line area CRUD in view

### ISSUE THREAD

**Issue by dayo2n** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#78]
# Description ✨
line area에서 CRUD 중 create, delete를 적용합니다

# TODO
- [ ] create
- [ ] delete
- 하다가 수정한 것들
  - [x] 처음 열린 plan board state를 쭉 가져가는 오류 수정
  - [ ] 탭바뷰의 닫는 버튼의 터치 영역이 너무 커서 x만 눌러지도록 수정
  - [x] 탭바간 이동하면 플랜보드뷰가 사라지는 오류
![ezgif com-video-to-gif (4)](https://github.com/DeveloperAcademy-POSTECH/MacC-Team15-Ampersand/assets/57654681/f126ad12-e029-4f7c-b2a6-1c4d7b58f869)
프로젝트보드 스토어가 PlanBoard에 대한 정보를 하나만 갖고 갈아끼우는 형식이고, 플젝보드뷰에서도 PlanBoardView는 하나만 열어놓고 데이터만 갈아끼우는 형식인데 플랜보드뷰가 onAppear가 세부 뷰에서 여기저기 불리는 상황이었음. 세부 뷰의 onAppear가 호출되어야 뷰도 세팅이 되는데 그렇지 않아서 발생한 문제 → 프로젝트 스토어가 플랜보드에 대한 모든 스토어를 갖도록 했습니다. projectItem을 가지는 것과 같은 양상입니다. 따라서 ProjectBoard < ProjectItem & PlanBoard ටㅇ
    - [ ] delete project (ProjectBoard: case .projectItemTapped(id: _, action: .binding(\.$isDeleted)):
