### ISSUE TITLE
[feat] Schedule CRUD

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#83]
# Description
ScheduleArea의 Schedule CRUD를 PlanBoard Store에서 작업합니다.
주로 Schedule들의 정렬과 관련한 작업을 진행합니다.
뷰와 연결하는 것은 새로 Issue를 생성해서 작업하겠습니다.

# TODO
- [x] Schedule 구조체 생성
- [x] Create 로직 생성
- [x] Delete 로직 생성
- [x] Update 로직 생성
