### ISSUE TITLE
[feat] Window Button 안으로 넣어서 쓸 수 있게 하기

### ISSUE THREAD

**Issue by Jin-s-work** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#86]
# Description ✨
Window Button과 TabBarView가 같이 있을 수 있게 만들거에요
그리고 최대화가 될 경우에는 Button을 없애고 홈버튼이 그 자리에 오게 해줄 거에요
Window Button과 TabBarView가 같이 있을 경우 ToolBar를, 
최대화가 될 경우 Window Button을 안보이게 하기 위해 ToolBar를 없앨 거에요

# TODO
- [x] Window Button와 TabBarView를 같이 있게 하기
- [x] 최대화가 될 경우 감지하여서 ToolBar를 없애서 WindowButton 자리에 TabBarView만 들어가게 하기
- [x] 최대화에서 다시 최소화가 될 경우 다시 ToolBar를 만들어서 WindowButton과 같이 있을 수 있게 하기
