### ISSUE TITLE
[feat] ScheduleArea View CRUD

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#88]
# Description
1. ScheduleArea의 View에 Store/Action을 붙입니다.
2. ScheduleArea의 디자인 변경 사항(여러 줄의 가로선 제거)을 반영합니다.
3. 그에 따른 Drag와 Schedule Create/Update 로직을 변경합니다.

# TODO
- [ ] 드래그 / 영역 전체 선택
- [ ] 엔터 / createSchedule Action 호출
- [ ] 엔터 / TextField 띄우기
- [ ] TextField / updateScheduleText 호출
- [ ] existingSchedules에 있는 Schedule을 뷰에 뿌리기
- [ ] DeleteSchedule
- [ ] updateDate
