### ISSUE TITLE
[feat] RIghtToolBarView 기능 개발

### ISSUE THREAD

**Issue by Jin-s-work** [DeveloperAcademy-POSTECH/MacC-Team15-Ampersand#91]
# Description ✨
RightToolBarView의 기능을 개발할거에요

# TODO
- [ ] RightToolBarView에 Schedule 들어가게 하기
- [ ] 클릭할 경우 그 일에 대한 정보 뜨게 하기
- [ ] Color 바꿀 수 있게 하기
